version: "3.3"
 
services:
    jenkins:
        image: jenkinsci/jenkins
        container_name: jenkins
        restart: always
        privileged: true
        ports:
            - "8080:8080"
            - "50000:50000"
        networks:
            - training-nw
        volumes:
            - jenkins_data:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - docker_certs:/certs/client:ro
    socat:
        image: alpine/socat:latest
        container_name: alpine-socat
        restart: always
        command: tcp-listen:2375, fork,reuseaddr unix-connect:/var/run/docker.sock
        networks:
            - training-nw
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        expose:
            - "2375"
networks:
    training-nw:
        driver: bridge
volumes:
    jenkins_data: {}
    docker_certs: {}
